<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGJoh83\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGJoh83/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCGJoh83.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCGJoh83\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCGJoh83\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CGJoh83',
    'container.build_id' => 'a89b0dd8',
    'container.build_time' => 1521736944,
));
